version: "3.8"
services:
  custom-container:
    image: angelostzourtzis/testcontainer:latest
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
